config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_for :admins
  get 'home/index'
  root to: "home#index"
  authenticate :admin do
    resources :categories
  end

  resources :products

  #La ruta del carrito con sus acciones
  resource :cart, only: [:show, :update]
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
    #Relationships
    has_and_belongs_to_many :products
end

app/models/order.rb
class Order < ApplicationRecord
  # Rlationships
  belongs_to :user
  has_many :order_items
  has_many :products, through: :order_items

  # validations
  validates :number, uniqueness: true

  # Siempre y cuando exista un producto y un stock mayor a cero puedo generar la orden
  def add_product(product_id, quantity)
    product = Product.find(product_id)
    if product && (product.stock > 0)
      order_items.create(product_id: product.id, quantity: quantity, price: product.price)
      total_value
    end
  end

  def total_value
    sum = 0
    order_items.each do |item|
      sum += item.price
    end
    update_attributes(total_value: sum)
  end
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
    # Relationships
    belongs_to :order
    belongs_to :product
end

app/models/product.rb
class Product < ApplicationRecord
    #Rlationships
    has_and_belongs_to_many :categories
    has_many :order_items
    has_many :orders, through: :order_items
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    #Esto evitara que otros usuarios se intercepten con el carrito del usuario actual
    def current_order
      if current_user
        order = Order.where(user_id: current_user.id).where(state: "created").last
        if order.nil?
          order = Order.create(user: current_user, state: "created")
        end
        return order
      end
      nil
    end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
    # Para poder utilizar el carrito se debe primero esta autenticado como usuario
    before_action :authenticate_user!
  
    def update
      product = params[:cart][:product_id]  #le pasamos el producto
      quantity = params[:cart][:quantity]   #le pasamos la cantidad
      current_order.add_product(product, quantity) #le pasamos la oredn actual con los atributos
      redirect_to root_url, notice: "Product added successfuly" #lo redireccionamos al root index
    end
  
    def show
      @order = current_order
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[ show edit update destroy ]

  # GET /categories or /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1 or /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories or /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to category_url(@category), notice: "Category was successfully created." }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to category_url(@category), notice: "Category was successfully updated." }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url, notice: "Category was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def category_params
      params.require(:category).permit(:name)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @products = Product.all
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i[ show edit update destroy ]

  # GET /products or /products.json
  def index
    @products = Product.all
  end

  # GET /products/1 or /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products or /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to product_url(@product), notice: "Product was successfully created." }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1 or /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to product_url(@product), notice: "Product was successfully updated." }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1 or /products/1.json
  def destroy
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url, notice: "Product was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(:name, :description, :stock, :price, :sku, { category_ids: [] })
    end
end

app/controllers/users/devise_controller.rb
class Users::DeviseController < ApplicationController
    class Responder < ActionController::Responder
      def to_turbo_stream
        controller.render(options.merge(formats: :html))
      rescue ActionView::MissingTemplate => error
        if get?
          raise error
        elsif has_errors? && default_action
          render rendering_options.merge(formats: :html, status: :unprocessable_entity)
        else
          redirect_to navigation_location
        end
      end
    end

    self.responder = Responder
    respond_to :html, :turbo_stream
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/carts/show.html.erb
<%= link_to "Vista principal", root_url %>
<% @order.order_items.includes(:product).each do |item| %>
  <p>
    <strong>Name:</strong>
    <%= item.product.name %>
  </p>
  <p>
    <strong>Name:</strong>
    <%= item.product.description %>
  </p>
  <p>
    <strong>Categories:</strong>
    <%= item.product.categories.name %>
  </p>
  <p>
    <strong>Price:</strong>
    <%= item.product.price %>
  </p>
  <p>
    <strong>Cant:</strong>
    <%= item.quantity %>
  </p>
  <p>
    <%#= link_to "Show this product", product %>
  </p>
<% end %>
<p>
  <strong>Total:</strong>
  <%= @order.total %>
</p>

app/views/categories/_category.html.erb
<div id="<%= dom_id category %>">
  <p>
    <strong>Name:</strong>
    <%= category.name %>
  </p>

</div>

app/views/categories/_form.html.erb
<%= form_with(model: category) do |form| %>
  <% if category.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render "form", category: @category %>

<br>

<div>
  <%= link_to "Show this category", @category %> |
  <%= link_to "Back to categories", categories_path %>
</div>

app/views/categories/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Categories</h1>

<div id="categories">
  <% @categories.each do |category| %>
    <%= render category %>
    <p>
      <%= link_to "Show this category", category %>
    </p>
  <% end %>
</div>

<%= link_to "New category", new_category_path %>

app/views/categories/new.html.erb
<h1>New category</h1>

<%= render "form", category: @category %>

<br>

<div>
  <%= link_to "Back to categories", categories_path %>
</div>

app/views/categories/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @category %>

<div>
  <%= link_to "Edit this category", edit_category_path(@category) %> |
  <%= link_to "Back to categories", categories_path %>

  <%= button_to "Destroy this category", @category, method: :delete %>
</div>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>
<div id="products">
  <% @products.each do |product| %>
    <p>
      <strong>Name:</strong>
      <%= product.name %>
    </p>
    <p>
      <strong>Categories:</strong>
      <%= product.categories.name %>
    </p>
    <p>
      <strong>Price:</strong>
      <%= product.price %>
    </p>
    <p>
      <%= link_to "Show this product", product %>
    </p>

    <p>
      <%= form_for :cart, url: cart_path, method: :put do |f| %>
        <%= f.hidden_field :product_id, value: product.id %>
        <%= f.hidden_field :quantity, value: 1 %>
        <%= f.submit "Add to cart" %>
      <% end %>
    </p>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ecommerce</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    
    <%# #Vistas bonitas %>
    <link rel="stylesheet" href="https://cdn.simplecss.org/simple.min.css">
    
    <%= javascript_importmap_tags %>
  </head>
  <body class="container">
    <%= render "shared/navbar" %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/products/_form.html.erb
<%= form_with(model: product) do |form| %>
  <% if product.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
        <% product.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :categories, style: "display: block" %>
    <%= form.collection_check_boxes(:category_ids, Category.all, :id, :name) do |b| %>
      <%= b.label class:"label-checkbox" do%>
        <%=b.check_box + b.text%>
      <%end%>
    <% end %>
  </div>

  <div>
    <%= form.label :stock, style: "display: block" %>
    <%= form.number_field :stock %>
  </div>

  <div>
    <%= form.label :price, style: "display: block" %>
    <%= form.text_field :price %>
  </div>

  <div>
    <%= form.label :sku, style: "display: block" %>
    <%= form.text_field :sku %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/products/_product.html.erb
<div id="<%= dom_id product %>">
  <p>
    <strong>Name:</strong>
    <%= product.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= product.description %>
  </p>

  <p>
    <strong>Stock:</strong>
    <%= product.stock %>
  </p>

  <p>
    <strong>Price:</strong>
    <%= product.price %>
  </p>

  <p>
    <strong>Sku:</strong>
    <%= product.sku %>
  </p>

</div>

app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render "form", product: @product %>

<br>

<div>
  <%= link_to "Show this product", @product %> |
  <%= link_to "Back to products", products_path %>
</div>

app/views/products/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Products</h1>

<div id="products">
  <% @products.each do |product| %>
    <%= render product %>
    <p>
      <%= link_to "Show this product", product %>
    </p>
  <% end %>
</div>

<%= link_to "New product", new_product_path %>

app/views/products/new.html.erb
<h1>New product</h1>

<%= render "form", product: @product %>

<br>

<div>
  <%= link_to "Back to products", products_path %>
</div>

app/views/products/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @product %>

<div>
  <%= link_to "Edit this product", edit_product_path(@product) %> |
  <%= link_to "Back to products", products_path %>

  <%= button_to "Destroy this product", @product, method: :delete %>
</div>

app/views/shared/_navbar.html.erb
<header>
  <nav>
    <%= link_to "Home", root_path %>
    <%= link_to "Products", products_path %>
    <%= link_to "New Product", new_product_path %>
  </nav>
  <% if current_admin %>
    <p>
      Hello <strong><%= current_admin.email %>!</strong>
      <p><%= link_to "Cerrar sesion", destroy_admin_session_path, 'data-turbo-method': :delete %></p>
    <% else %>
      <p>
        No has iniciado sesion aun!!!
        <%= link_to "Registrarte!", new_admin_registration_path %>
        <%= link_to "Inicia sesion!", new_admin_session_path %>
      </p>
    <% end %>
</header>